// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createRefresh_tokens = `-- name: CreateRefresh_tokens :one
INSERT INTO refresh_tokens (token, created_at, updated_at, user_id, expires_at,revoked_at)
VALUES (
    $1,
    NOW(),
    NOW(),
    $2,
    NOW() + INTERVAL '60 days',
    NULL
)
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type CreateRefresh_tokensParams struct {
	Token  string
	UserID uuid.UUID
}

func (q *Queries) CreateRefresh_tokens(ctx context.Context, arg CreateRefresh_tokensParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createRefresh_tokens, arg.Token, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRefresh_tokenByToken = `-- name: GetRefresh_tokenByToken :one
SELECT token, created_at, updated_at, user_id, expires_at, revoked_at FROM refresh_tokens WHERE token = $1
`

func (q *Queries) GetRefresh_tokenByToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getRefresh_tokenByToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserFromRefreshToken = `-- name: GetUserFromRefreshToken :one
SELECT u.id, u.created_at, u.updated_at, u.email, u.hashed_password
FROM refresh_tokens rt
JOIN users u ON rt.user_id = u.id
WHERE
  rt.token = $1
  AND rt.expires_at > NOW()
  AND rt.revoked_at IS NULL
`

func (q *Queries) GetUserFromRefreshToken(ctx context.Context, token string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserFromRefreshToken, token)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}

const updateRefreshTokenRevoke = `-- name: UpdateRefreshTokenRevoke :exec
UPDATE refresh_tokens 
SET updated_at = NOW(),revoked_at = NOW()
WHERE token = $1
`

func (q *Queries) UpdateRefreshTokenRevoke(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, updateRefreshTokenRevoke, token)
	return err
}
